name: 'OneStream Utils'
description: 'XFProject related OneStream utilities'
author: 'GrnFba'
inputs: 
  osAction:
    description: 'Action to execute'
    required: true
    default: ''
  osTempName:
    description: 'TempName'
    required: false
    default: 'xxxyyyzzz'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "\"${{ inputs.osAction }}\""
    - "\"${{ inputs.osTempName }}\""
